#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v27
# autospec commit: 65cf152
#
# Source0 file verified with key 0xC8464D549AF75C0A (pluknet@nginx.com)
#
Name     : nginx-mainline
Version  : 1.29.0
Release  : 133
URL      : https://nginx.org/download/nginx-1.29.0.tar.gz
Source0  : https://nginx.org/download/nginx-1.29.0.tar.gz
Source1  : nginx-mainline-setup.service
Source2  : nginx-mainline.service
Source3  : nginx-mainline.tmpfiles
Source4  : https://nginx.org/download/nginx-1.29.0.tar.gz.asc
Source5  : C8464D549AF75C0A.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nginx-mainline-bin = %{version}-%{release}
Requires: nginx-mainline-config = %{version}-%{release}
Requires: nginx-mainline-data = %{version}-%{release}
Requires: nginx-mainline-lib = %{version}-%{release}
Requires: nginx-mainline-license = %{version}-%{release}
Requires: nginx-mainline-services = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gnupg
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Build-do-not-exit-after-unknown-option.patch
Patch2: 0002-Rework-nginx-configuration-directories.patch
Patch3: 0004-Add-nginx-module-build-install-script.patch

%description
geo2nginx.pl 		by Andrei Nigmatulin
The perl script to convert CSV geoip database ( free download
at http://www.maxmind.com/app/geoip_country ) to format, suitable
for use by the ngx_http_geo_module.

%package bin
Summary: bin components for the nginx-mainline package.
Group: Binaries
Requires: nginx-mainline-data = %{version}-%{release}
Requires: nginx-mainline-config = %{version}-%{release}
Requires: nginx-mainline-license = %{version}-%{release}
Requires: nginx-mainline-services = %{version}-%{release}

%description bin
bin components for the nginx-mainline package.


%package config
Summary: config components for the nginx-mainline package.
Group: Default

%description config
config components for the nginx-mainline package.


%package data
Summary: data components for the nginx-mainline package.
Group: Data

%description data
data components for the nginx-mainline package.


%package dev
Summary: dev components for the nginx-mainline package.
Group: Development
Requires: nginx-mainline-lib = %{version}-%{release}
Requires: nginx-mainline-bin = %{version}-%{release}
Requires: nginx-mainline-data = %{version}-%{release}
Provides: nginx-mainline-devel = %{version}-%{release}
Requires: nginx-mainline = %{version}-%{release}

%description dev
dev components for the nginx-mainline package.


%package extras-modulebuild
Summary: extras-modulebuild components for the nginx-mainline package.
Group: Default

%description extras-modulebuild
extras-modulebuild components for the nginx-mainline package.


%package lib
Summary: lib components for the nginx-mainline package.
Group: Libraries
Requires: nginx-mainline-data = %{version}-%{release}
Requires: nginx-mainline-license = %{version}-%{release}

%description lib
lib components for the nginx-mainline package.


%package license
Summary: license components for the nginx-mainline package.
Group: Default

%description license
license components for the nginx-mainline package.


%package services
Summary: services components for the nginx-mainline package.
Group: Systemd services
Requires: systemd

%description services
services components for the nginx-mainline package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE5}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE4} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) C8464D549AF75C0A' gpg.status
%setup -q -n nginx-1.29.0
cd %{_builddir}/nginx-1.29.0
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750862841
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --prefix=/var/www \
--conf-path=/usr/share/nginx-mainline/conf/nginx.conf \
--sbin-path=/usr/bin/nginx-mainline \
--pid-path=/run/nginx-mainline.pid \
--lock-path=/run/lock/nginx-mainline.lock \
--modules-path=/usr/lib64/nginx-mainline \
--http-log-path=syslog:server=unix:/dev/log \
--error-log-path=stderr \
--http-client-body-temp-path=/var/lib/nginx-mainline/client-body \
--http-fastcgi-temp-path=/var/lib/nginx-mainline/fastcgi \
--http-proxy-temp-path=/var/lib/nginx-mainline/proxy \
--http-scgi-temp-path=/var/lib/nginx-mainline/scgi \
--http-uwsgi-temp-path=/var/lib/nginx-mainline/uwsgi \
--user=httpd \
--group=httpd \
--with-threads \
--with-debug \
--with-compat \
--with-file-aio \
--with-http_addition_module \
--with-http_auth_request_module \
--with-http_dav_module \
--with-http_degradation_module \
--with-http_flv_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_realip_module \
--with-http_secure_link_module \
--with-http_slice_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_sub_module \
--with-http_v2_module \
--with-mail \
--with-mail_ssl_module \
--with-poll_module \
--with-select_module \
--with-stream=dynamic \
--with-stream_realip_module \
--with-stream_ssl_module \
--with-stream_ssl_preread_module
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1750862841
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nginx-mainline
cp %{_builddir}/nginx-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/nginx-mainline/1d0310b0a6d114086ca3a8de25e8affe9cb16813 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/nginx-mainline-setup.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/nginx-mainline.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/tmpfiles.d/nginx-mainline.conf
## install_append content
# these are just copies
rm -f %{buildroot}/usr/share/nginx-mainline/conf/*.default
# template configuration
install -m0644 conf/server.conf.example %{buildroot}/usr/share/nginx-mainline/conf/
install -m0644 conf/nginx.conf.example %{buildroot}/usr/share/nginx-mainline/conf/
# move these to a "template" location
mkdir -p %{buildroot}/usr/share/nginx-mainline/html
mv %{buildroot}/var/www/html/* %{buildroot}/usr/share/nginx-mainline/html/ || :

mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/nginx-mainline.service %{buildroot}/usr/share/clr-service-restart/nginx-mainline.service

# nginx module build infra
install -m0755 nginx-module %{buildroot}/usr/bin
%{buildroot}/usr/bin/nginx-module asset-install %{buildroot}
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nginx-mainline

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/nginx-mainline.conf

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/nginx-mainline.service
/usr/share/nginx-mainline/conf/fastcgi.conf
/usr/share/nginx-mainline/conf/fastcgi_params
/usr/share/nginx-mainline/conf/koi-utf
/usr/share/nginx-mainline/conf/koi-win
/usr/share/nginx-mainline/conf/mime.types
/usr/share/nginx-mainline/conf/nginx.conf
/usr/share/nginx-mainline/conf/nginx.conf.example
/usr/share/nginx-mainline/conf/scgi_params
/usr/share/nginx-mainline/conf/server.conf.example
/usr/share/nginx-mainline/conf/uwsgi_params
/usr/share/nginx-mainline/conf/win-utf
/usr/share/nginx-mainline/html/50x.html
/usr/share/nginx-mainline/html/index.html

%files dev
%defattr(-,root,root,-)
/usr/include/nginx-mainline/configure
/usr/include/nginx-mainline/core/nginx.h
/usr/include/nginx-mainline/core/ngx_array.h
/usr/include/nginx-mainline/core/ngx_bpf.h
/usr/include/nginx-mainline/core/ngx_buf.h
/usr/include/nginx-mainline/core/ngx_conf_file.h
/usr/include/nginx-mainline/core/ngx_config.h
/usr/include/nginx-mainline/core/ngx_connection.h
/usr/include/nginx-mainline/core/ngx_core.h
/usr/include/nginx-mainline/core/ngx_crc.h
/usr/include/nginx-mainline/core/ngx_crc32.h
/usr/include/nginx-mainline/core/ngx_crypt.h
/usr/include/nginx-mainline/core/ngx_cycle.h
/usr/include/nginx-mainline/core/ngx_file.h
/usr/include/nginx-mainline/core/ngx_hash.h
/usr/include/nginx-mainline/core/ngx_inet.h
/usr/include/nginx-mainline/core/ngx_list.h
/usr/include/nginx-mainline/core/ngx_log.h
/usr/include/nginx-mainline/core/ngx_md5.h
/usr/include/nginx-mainline/core/ngx_module.h
/usr/include/nginx-mainline/core/ngx_murmurhash.h
/usr/include/nginx-mainline/core/ngx_open_file_cache.h
/usr/include/nginx-mainline/core/ngx_palloc.h
/usr/include/nginx-mainline/core/ngx_parse.h
/usr/include/nginx-mainline/core/ngx_parse_time.h
/usr/include/nginx-mainline/core/ngx_proxy_protocol.h
/usr/include/nginx-mainline/core/ngx_queue.h
/usr/include/nginx-mainline/core/ngx_radix_tree.h
/usr/include/nginx-mainline/core/ngx_rbtree.h
/usr/include/nginx-mainline/core/ngx_regex.h
/usr/include/nginx-mainline/core/ngx_resolver.h
/usr/include/nginx-mainline/core/ngx_rwlock.h
/usr/include/nginx-mainline/core/ngx_sha1.h
/usr/include/nginx-mainline/core/ngx_shmtx.h
/usr/include/nginx-mainline/core/ngx_slab.h
/usr/include/nginx-mainline/core/ngx_string.h
/usr/include/nginx-mainline/core/ngx_syslog.h
/usr/include/nginx-mainline/core/ngx_thread_pool.h
/usr/include/nginx-mainline/core/ngx_times.h
/usr/include/nginx-mainline/event/modules/ngx_iocp_module.h
/usr/include/nginx-mainline/event/ngx_event.h
/usr/include/nginx-mainline/event/ngx_event_connect.h
/usr/include/nginx-mainline/event/ngx_event_openssl.h
/usr/include/nginx-mainline/event/ngx_event_pipe.h
/usr/include/nginx-mainline/event/ngx_event_posted.h
/usr/include/nginx-mainline/event/ngx_event_timer.h
/usr/include/nginx-mainline/event/ngx_event_udp.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_ack.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_connection.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_connid.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_frames.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_migration.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_openssl_compat.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_output.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_protection.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_socket.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_ssl.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_streams.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_tokens.h
/usr/include/nginx-mainline/event/quic/ngx_event_quic_transport.h
/usr/include/nginx-mainline/http/modules/ngx_http_ssi_filter_module.h
/usr/include/nginx-mainline/http/modules/ngx_http_ssl_module.h
/usr/include/nginx-mainline/http/modules/perl/ngx_http_perl_module.h
/usr/include/nginx-mainline/http/ngx_http.h
/usr/include/nginx-mainline/http/ngx_http_cache.h
/usr/include/nginx-mainline/http/ngx_http_config.h
/usr/include/nginx-mainline/http/ngx_http_core_module.h
/usr/include/nginx-mainline/http/ngx_http_request.h
/usr/include/nginx-mainline/http/ngx_http_script.h
/usr/include/nginx-mainline/http/ngx_http_upstream.h
/usr/include/nginx-mainline/http/ngx_http_upstream_round_robin.h
/usr/include/nginx-mainline/http/ngx_http_variables.h
/usr/include/nginx-mainline/http/v2/ngx_http_v2.h
/usr/include/nginx-mainline/http/v2/ngx_http_v2_module.h
/usr/include/nginx-mainline/http/v3/ngx_http_v3.h
/usr/include/nginx-mainline/http/v3/ngx_http_v3_encode.h
/usr/include/nginx-mainline/http/v3/ngx_http_v3_parse.h
/usr/include/nginx-mainline/http/v3/ngx_http_v3_table.h
/usr/include/nginx-mainline/http/v3/ngx_http_v3_uni.h
/usr/include/nginx-mainline/mail/ngx_mail.h
/usr/include/nginx-mainline/mail/ngx_mail_imap_module.h
/usr/include/nginx-mainline/mail/ngx_mail_pop3_module.h
/usr/include/nginx-mainline/mail/ngx_mail_smtp_module.h
/usr/include/nginx-mainline/mail/ngx_mail_ssl_module.h
/usr/include/nginx-mainline/os/unix/ngx_alloc.h
/usr/include/nginx-mainline/os/unix/ngx_atomic.h
/usr/include/nginx-mainline/os/unix/ngx_channel.h
/usr/include/nginx-mainline/os/unix/ngx_darwin.h
/usr/include/nginx-mainline/os/unix/ngx_darwin_config.h
/usr/include/nginx-mainline/os/unix/ngx_dlopen.h
/usr/include/nginx-mainline/os/unix/ngx_errno.h
/usr/include/nginx-mainline/os/unix/ngx_files.h
/usr/include/nginx-mainline/os/unix/ngx_freebsd.h
/usr/include/nginx-mainline/os/unix/ngx_freebsd_config.h
/usr/include/nginx-mainline/os/unix/ngx_gcc_atomic_amd64.h
/usr/include/nginx-mainline/os/unix/ngx_gcc_atomic_ppc.h
/usr/include/nginx-mainline/os/unix/ngx_gcc_atomic_sparc64.h
/usr/include/nginx-mainline/os/unix/ngx_gcc_atomic_x86.h
/usr/include/nginx-mainline/os/unix/ngx_linux.h
/usr/include/nginx-mainline/os/unix/ngx_linux_config.h
/usr/include/nginx-mainline/os/unix/ngx_os.h
/usr/include/nginx-mainline/os/unix/ngx_posix_config.h
/usr/include/nginx-mainline/os/unix/ngx_process.h
/usr/include/nginx-mainline/os/unix/ngx_process_cycle.h
/usr/include/nginx-mainline/os/unix/ngx_setaffinity.h
/usr/include/nginx-mainline/os/unix/ngx_setproctitle.h
/usr/include/nginx-mainline/os/unix/ngx_shmem.h
/usr/include/nginx-mainline/os/unix/ngx_socket.h
/usr/include/nginx-mainline/os/unix/ngx_solaris.h
/usr/include/nginx-mainline/os/unix/ngx_solaris_config.h
/usr/include/nginx-mainline/os/unix/ngx_sunpro_atomic_sparc64.h
/usr/include/nginx-mainline/os/unix/ngx_thread.h
/usr/include/nginx-mainline/os/unix/ngx_time.h
/usr/include/nginx-mainline/os/unix/ngx_user.h
/usr/include/nginx-mainline/os/win32/ngx_alloc.h
/usr/include/nginx-mainline/os/win32/ngx_atomic.h
/usr/include/nginx-mainline/os/win32/ngx_dlopen.h
/usr/include/nginx-mainline/os/win32/ngx_errno.h
/usr/include/nginx-mainline/os/win32/ngx_files.h
/usr/include/nginx-mainline/os/win32/ngx_os.h
/usr/include/nginx-mainline/os/win32/ngx_process.h
/usr/include/nginx-mainline/os/win32/ngx_process_cycle.h
/usr/include/nginx-mainline/os/win32/ngx_shmem.h
/usr/include/nginx-mainline/os/win32/ngx_socket.h
/usr/include/nginx-mainline/os/win32/ngx_thread.h
/usr/include/nginx-mainline/os/win32/ngx_time.h
/usr/include/nginx-mainline/os/win32/ngx_user.h
/usr/include/nginx-mainline/os/win32/ngx_win32_config.h
/usr/include/nginx-mainline/stream/ngx_stream.h
/usr/include/nginx-mainline/stream/ngx_stream_script.h
/usr/include/nginx-mainline/stream/ngx_stream_ssl_module.h
/usr/include/nginx-mainline/stream/ngx_stream_upstream.h
/usr/include/nginx-mainline/stream/ngx_stream_upstream_round_robin.h
/usr/include/nginx-mainline/stream/ngx_stream_variables.h

%files extras-modulebuild
%defattr(-,root,root,-)
/usr/bin/nginx-module
/usr/share/nginx-mainline/module-build/auto/cc/acc
/usr/share/nginx-mainline/module-build/auto/cc/bcc
/usr/share/nginx-mainline/module-build/auto/cc/ccc
/usr/share/nginx-mainline/module-build/auto/cc/clang
/usr/share/nginx-mainline/module-build/auto/cc/conf
/usr/share/nginx-mainline/module-build/auto/cc/gcc
/usr/share/nginx-mainline/module-build/auto/cc/icc
/usr/share/nginx-mainline/module-build/auto/cc/msvc
/usr/share/nginx-mainline/module-build/auto/cc/name
/usr/share/nginx-mainline/module-build/auto/cc/owc
/usr/share/nginx-mainline/module-build/auto/cc/sunc
/usr/share/nginx-mainline/module-build/auto/define
/usr/share/nginx-mainline/module-build/auto/endianness
/usr/share/nginx-mainline/module-build/auto/feature
/usr/share/nginx-mainline/module-build/auto/have
/usr/share/nginx-mainline/module-build/auto/have_headers
/usr/share/nginx-mainline/module-build/auto/headers
/usr/share/nginx-mainline/module-build/auto/include
/usr/share/nginx-mainline/module-build/auto/init
/usr/share/nginx-mainline/module-build/auto/install
/usr/share/nginx-mainline/module-build/auto/lib/conf
/usr/share/nginx-mainline/module-build/auto/lib/geoip/conf
/usr/share/nginx-mainline/module-build/auto/lib/google-perftools/conf
/usr/share/nginx-mainline/module-build/auto/lib/libatomic/conf
/usr/share/nginx-mainline/module-build/auto/lib/libatomic/make
/usr/share/nginx-mainline/module-build/auto/lib/libgd/conf
/usr/share/nginx-mainline/module-build/auto/lib/libxslt/conf
/usr/share/nginx-mainline/module-build/auto/lib/make
/usr/share/nginx-mainline/module-build/auto/lib/openssl/conf
/usr/share/nginx-mainline/module-build/auto/lib/openssl/make
/usr/share/nginx-mainline/module-build/auto/lib/openssl/makefile.bcc
/usr/share/nginx-mainline/module-build/auto/lib/openssl/makefile.msvc
/usr/share/nginx-mainline/module-build/auto/lib/pcre/conf
/usr/share/nginx-mainline/module-build/auto/lib/pcre/make
/usr/share/nginx-mainline/module-build/auto/lib/pcre/makefile.bcc
/usr/share/nginx-mainline/module-build/auto/lib/pcre/makefile.msvc
/usr/share/nginx-mainline/module-build/auto/lib/pcre/makefile.owc
/usr/share/nginx-mainline/module-build/auto/lib/perl/conf
/usr/share/nginx-mainline/module-build/auto/lib/perl/make
/usr/share/nginx-mainline/module-build/auto/lib/zlib/conf
/usr/share/nginx-mainline/module-build/auto/lib/zlib/make
/usr/share/nginx-mainline/module-build/auto/lib/zlib/makefile.bcc
/usr/share/nginx-mainline/module-build/auto/lib/zlib/makefile.msvc
/usr/share/nginx-mainline/module-build/auto/lib/zlib/makefile.owc
/usr/share/nginx-mainline/module-build/auto/make
/usr/share/nginx-mainline/module-build/auto/module
/usr/share/nginx-mainline/module-build/auto/modules
/usr/share/nginx-mainline/module-build/auto/nohave
/usr/share/nginx-mainline/module-build/auto/options
/usr/share/nginx-mainline/module-build/auto/os/conf
/usr/share/nginx-mainline/module-build/auto/os/darwin
/usr/share/nginx-mainline/module-build/auto/os/freebsd
/usr/share/nginx-mainline/module-build/auto/os/linux
/usr/share/nginx-mainline/module-build/auto/os/solaris
/usr/share/nginx-mainline/module-build/auto/os/win32
/usr/share/nginx-mainline/module-build/auto/sources
/usr/share/nginx-mainline/module-build/auto/stubs
/usr/share/nginx-mainline/module-build/auto/summary
/usr/share/nginx-mainline/module-build/auto/threads
/usr/share/nginx-mainline/module-build/auto/types/sizeof
/usr/share/nginx-mainline/module-build/auto/types/typedef
/usr/share/nginx-mainline/module-build/auto/types/uintptr_t
/usr/share/nginx-mainline/module-build/auto/types/value
/usr/share/nginx-mainline/module-build/auto/unix
/usr/share/nginx-mainline/module-build/configure

%files lib
%defattr(-,root,root,-)
/usr/lib64/nginx-mainline/ngx_stream_module.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nginx-mainline/1d0310b0a6d114086ca3a8de25e8affe9cb16813

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/nginx-mainline-setup.service
/usr/lib/systemd/system/nginx-mainline.service
